batch_size: 4  # total: 4*6
iters: 50000

train_dataset:
  type: Dataset
  dataset_root: /kaggle/input/golf_header
  num_classes: 3
  mode: train
  train_path: /kaggle/input/golf_header/train.txt
  transforms:
    - type: RandomAffine
      max_rotation: 180
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.5
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [960, 960]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: RandomBlur
      prob: 0.5
      blur_type: random
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: /kaggle/input/golf_header
  num_classes: 3
  mode: val
  val_path: /kaggle/input/golf_header/val.txt
  transforms:
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 250000   # batch_size * 960 * 720 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 250000
    - type: OhemCrossEntropyLoss
      min_kept: 250000
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
